# Linear Algebra Final Project: Infected Decease Model

## 1. Introduction
โปรเจคนี้เป็นการนำเสนอและวิเคราะห์อัตราการแพร่เชื้อด้วยคณิตศาสตร์ โดยจะกำหนดให้ 
- **s<sub>t</sub>** แทนเปอร์เซ็นต์ของประชากรทั้งหมดที่มีความเสี่ยงที่จะติดเชื้อ ณเวลา t
- **i<sub>t</sub>** แทนเปอร์เซ็นต์ของประชากรที่ติดเชื้อ ณเวลา t
- **r<sub>t</sub>** แทนเปอร์เซ็นต์ของประชากรที่หายแล้ว ณเวลา t

ซึ่งอัตราการเปลี่ยนสถานะการติดเชื้อของประชากรคือ
$$
  s_{t} = 0.95s_{t-1} +   0i_{t-1}  + 0.15r_{t-1}\\
  i_{t} = 0.05s_{t-1} + 0.80i_{t-1} + 0r_{t-1} \\
  r_{t} = 0s_{t-1}    + 0.20i_{t-1} + 0.85r_{t-1}
$$
ซึ่งจากสมการข้างต้นสามารถอธิบายได้ว่า
- ในรอบสัปดาห์ที่ t จำนวนผู้ที่เสี่ยงต่อการติดเชื้อจะเท่ากับ 95%ของผู้ที่มีความเสี่ยงสูงที่จะติดเชื้อจากสัปดาห์ก่อน ร่วมกับ15%ของผู้ที่หายจากการติดเชื้อจากสัปดาห์ก่อน
- ในรอบสัปดาห์ที่ t จำนวนผู้ที่ติดเชื้อจะเท่ากับ 5%ของผู้ที่มีความเสี่ยงสูงที่จะติดเชื้อจากสัปดาห์ก่อน ร่วมกับ 80%ของผู้ที่ติดเชื้อจากสัปดาห์ก่อน
- ในรอบสัปดาห์ที่ t จำนวนผู้ที่หายจะเท่ากับ 20%ของผู้ที่ติดเชื้อจากสัปดาห์ก่อน ร่วมกับ 85%ของผู้ที่หายจากการติดเชื้อจากสัปดาห์ก่อน

โดยสมการข้างต้นสามารถเขียนเป็นรูปของ matrix ได้ดังนี้
$$
A =  \begin{bmatrix}
0.95 & 0 & 0.15\\
0.05 & 0.80 & 0\\
0 & 0.20 & 0.85
\end{bmatrix}
$$

## 2. การหาผู้ติดเชื้อของสัปดาห์ต่อๆไป
สำหรับการหาผู้ติดเชื้อของสัปดาห์ต่อๆไปเมื่อ $X_{0}$ คือค่าสถาณะการติดเชื้อเริ่มต้นซึ่งมีค่าเป็น $\begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix} $ โดยจะใช้สมการ  $s_{t} = As_{t-1}$ ซึ่งสามารถเขียนเป็นรูปของ matrix ได้ดังนี้
$$
X_{t} = AX_{0} \\
X_{t} = \begin{bmatrix}
0.95 & 0 & 0.15\\
0.05 & 0.80 & 0\\
0 & 0.20 & 0.85
\end{bmatrix} \begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix} = AX_{t-1}
$$
โดยสามารถเขียนโค้ดเพื่อหาค่าของ $X_{t}$ ได้ดังนี้

In [1]:
import numpy as np
A = np.array([[0.95, 0, 0.15],[0.05,0.8,0],[0,0.2,0.85]])
## X at time 0
X_0 = np.array([[0.95],[0.05],[0]])

จากโค้ดข้างต้นเป็นขั้นตอนการเริ่มต้นการคำนวณหาสถานะผู้ติดเชื้อโดย
```python
A = np.array([[0.95, 0, 0.15], [0.05, 0.80, 0], [0, 0.20, 0.85]])
```
เป็นการตั้งmatrix A โดยมีค่าตามที่กล่าวไว้ในหัวข้อที่ 1 และ
```python
X0 = np.array([[0.95], [0.05], [0]])
```
เป็นการตั้งค่าสถานะติดเชื้อเริ่มต้น โดยมีค่าตามที่กล่าวไว้ในหัวข้อที่ 1

จากนั้นทำการทดลองหาค่าสถาณะการติดเชื้อในสัปดาห์ที่ 1จาก
$$
X_{1} = AX_{0} = A \begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix} = A \begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix}

In [2]:
X_1 = A@X_0
X_1

array([[0.9025],
       [0.0875],
       [0.01  ]])

ทดลองทำการการสัปดาห์ที่สอง และสามจากสมการ
$$
X_{2} = AX_{1} = A \begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix} = A \begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix} \\
และ \\
X_{3} = AX_{2} = A \begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix} = A \begin{bmatrix} 0.95\\ 0.05\\ 0 \end{bmatrix}
$$

In [3]:
X_2 = A@X_1
X_2

array([[0.858875],
       [0.115125],
       [0.026   ]])

In [4]:
X_3 = A@X_2
X_3

array([[0.81983125],
       [0.13504375],
       [0.045125  ]])

ซึ่งจากการหา $X_{2} $ และ $ X_{3}$ สามารถเขียนเป็นสมการได้ตามสมการด้านล่าง
$$
X_{1} = AX_{0} \\
X_{2} = AX_{1} = AAX_{0} = A^{2}X_{0}\\
X_{3} = AX_{2} = AAX_{2} = A^{3}X_{0}\\
$$
ซึ่งจากรูปแบบที่กล่าวข้างต้นสามารถเขียนเป็นรูปทั่วไปได้ดังนี้
$$
X_{t} = A^{t}X_{0}
$$

ซึ่งเราสามารถประยุกต์สมการข้างต้นไปใช้ในการเขียนโค้ดได้ตาม cellด้านล่าง

In [5]:
X = np.array([[0.95],[0.05],[0]])
def findXt(A, X, t):
  for i in range(t):
    X = A@X
  return X
findXt(A, X, 2)

array([[0.858875],
       [0.115125],
       [0.026   ]])

สำหรับรูปแบบสมการข้างต้นสามารถเปรียบเทียบได้กับการทำแปลงเชิงเส้นหรือสามารถเขียนเป็นรูปสมการได้ดังนี้
$$
ให้ \quad T: \mathbb{M_{3x1}} \rightarrow \mathbb{M_{3x1}} \quad เป็นการแปลงเชิงเส้นซึ่ง \\
T(X_{t}) = A^{t}X_{0} \\  
$$

ซึ่งการแปลงเชิงเส้นรุปแบบนี้ ยิ่งมีค่าเวลาผ่านไปนานขึ้นหรือจำนวนtสูงขึ้นจะมีผลทำให้เวลาในการหาค่าของสมการเพิ่มขึ้นเรื่อยๆโดยเราสามารถประยุกต์ **eigen value** และ **eigen vector** ในการหาเมทริกซ์สถานะการติดเชื้อของสัปดาห์นั้นๆได้

## 3.การหาผู้ติดเชื้อในสัปดาห์ต่อๆไปด้วย Eigen Value และ Eigen Vector
สำหรับการหาค่าสถาณะการติดเชื้อในสัปดาห์ต่อๆไปนั้นจำเป็นจะต้องเข้าใจการใช้งานค่าเจาะจง และเวคเตอร์เจาะจงเสียก่อน <br>
โดยให้ $ T: V \rightarrow V $ เป็นการแปลงเชิงเส้นบนปริภูมิเวคเตอร์ V และจะเรียก $ \lambda \in  \mathbb{F} $ ว่า **ค่าเจาะจง(Eigen Value)** ของ T ถ้ามีเวคเตอร์ $ v \in V $ ที่ไม่ใช่เวคเตอร์ศูนย์ซึ่ง
$$
T(v) = \lambda V
$$

ซึ่งในการเขียนโปรแกรม เราสามารถใช้method ของ`numpy` ในการหา **Eigen Value** และ **Eigen Vector** ได้ซึ่งในการทดลองครั้งนี้ จะใช้การทำ **diagonalization(D)** ในการหา A เพื่อนำไปแทนในฟังก์ชั่น การแปลงเชิงเส้นโดยที่
$$
D = P^{-1}AP
$$
ซึ่งในกรณีนี้เราจำเป็นต้องหา A แทน D จึงทำการคูณข้างหน้าด้วย P และคูณด้านหลังด้วย P<sup>-1</sup>ทำให้ได้สมการดังต่อไปนี้
$$
D = P^{-1}AP \\
PD = PP^{-1}AP = AP \\
PDP^{-1} = APP^{-1} = A\\
\therefore A = PDP^{-1}
$$

จากนั้นนำ A ไปแทนในสมการที่กล่าวไปในหัวข้อที่2. จาก
$$
X_{t} = A^{t}X_{0} \\
$$
แทน A ด้วย $ PDP^{-1} $ โดยการยกกำลังด้วย t นั้นสามารถทำการยกกำลัง t แทนได้ภายในเมริกซ์ทแยง(D)จาก
$$
A^{k} = PD^{k}P^{-1}
เมื่อ D = \begin{bmatrix}
\lambda^k_1 & 0 & ... & 0\\
0 & \lambda^k_2 & ... & 0\\
... & ... & ... & ... \\
0 & 0 & ... & \lambda^k_n
\end{bmatrix}
$$

โดยเริ่มต้นจากการหาค่า **Eigen Value** และ **Eigen Vector** จากฟังก์ชั่นด้านล่าง

In [6]:
eigenVal, eigenVec = np.linalg.eig(A)

In [7]:
eigenVal

array([1. +0.j        , 0.8+0.08660254j, 0.8-0.08660254j])

ทำการตั้งค่า `P` ให้เท่ากับค่าของ `eigenVec` ที่ออกมาจากฟังก์ชั่นด้านบน

In [8]:
P = eigenVec

หา $ P^{-1}$ ด้วย `numpy.linalg.inv()`

In [9]:
PInverse = np.linalg.inv(P)

In [10]:
PInverse

array([[-0.68421053+6.01370805e-17j, -0.68421053-1.20274161e-16j,
        -0.68421053+6.01370805e-17j],
       [-0.14886459+3.43788034e-01j, -0.14886459-1.28920513e+00j,
         0.5582422 -6.44602564e-02j],
       [-0.14886459-3.43788034e-01j, -0.14886459+1.28920513e+00j,
         0.5582422 +6.44602564e-02j]])

จากนั้นนำ ค่า**Eigen Value** ที่ได้แทนเข้าไปที่ตำแหน่งตามแนวทแยงแล้วแทนด้วยตัวแปร D และสร้างฟังก์ชั่นที่สามารถยกกำลังค่าด้านใน Dได้ด้วยฟังก์ชั่น
```python
def SetLanbda(D, exp):
  ...
  return newD
```
โดยที่ส่งparameter D ที่เป็นเมทริกซ์ทแยงเริ่ม้น และ exp เป็นเลขที่ต้องการจะยกกำลัง หรือ t

In [11]:
D = np.array([[eigenVal[0], 0, 0],
            [0, eigenVal[1], 0],
            [0, 0, eigenVal[2]]])
def SetLambda(D: np.array,exp: int):
  newD = np.copy(D)
  newD[0][0] = newD[0][0]**exp
  newD[1][1] = newD[1][1]**exp
  newD[2][2] = newD[2][2]**exp
  return newD

In [12]:
Dexp2 = SetLambda(D, 2)
Dexp2

array([[1.    +0.j        , 0.    +0.j        , 0.    +0.j        ],
       [0.    +0.j        , 0.6325+0.13856406j, 0.    +0.j        ],
       [0.    +0.j        , 0.    +0.j        , 0.6325-0.13856406j]])

นำค่าที่ได้มาทุกค่ามาทำการคูณกันตามรูปสามการ
$$
 X_{t} = AX_{0} \\
 X_{t} = PD^{t}P^{-1}X_{0}
$$

In [13]:
Xt = P@Dexp2@PInverse@X_0

In [14]:
D = np.array([[eigenVal[0]**3, 0, 0],
            [0, eigenVal[1]**3, 0],
            [0, 0, eigenVal[2]**3]])
  
X_3Eigen = D@X_0
X_3Eigen.real

X_3Eigen

array([[0.95  +0.j        ],
       [0.0247+0.00828137j],
       [0.    +0.j        ]])

## 4. ตอบคำถามท้ายการทดลอง

1. ระหว่างการหา X<sub>t</sub> ด้วยการแปลงเชิงเส้นธรรมดา เทียบกับการใช้ **Eigen Value** และ **Eigen Vector** แบบใดมีประวิทธิภาพมากกว่ากัน <br>
**คำตอบ** การแปลงเชิงเส้นแบบธรรมดานั้นจะมีประสิธิภาพมากกว่าเมื่อมีจำนวน tที่น้อยมากๆ แต่การใช้**Eigen Value** และ **Eigen Vector** จะมีประสิทธิภาพเมื่อt มีค่าที่สูงมากๆ

In [15]:
import time

เทียบเวลาเมื่อต้องการหา t ที่ค่า 5

In [16]:
X = np.array([[0.95],[0.05],[0]])
A = np.array([[0.95, 0, 0.15],[0.05,0.8,0],[0,0.2,0.85]])
def findXt(A, X, t):
  for i in range(t):
    X = A@X
  return X
t5TransformationStart = time.perf_counter_ns()
outt5Trans = findXt(A, X, 5)
t5TransformationEnd = time.perf_counter_ns()
t5TransTime = t5TransformationEnd - t5TransformationStart
print(f"\033[4mtransformation\033[00m runtime when t= 5: \033[92m {t5TransTime} \033[00m ns")
print(f"Value: {outt5Trans} ")

transformation runtime when t= 5:  68700  ns
Value: [[0.75613277]
 [0.15850167]
 [0.08536556]] 


In [17]:
X0 = np.array([[0.95],[0.05],[0]])
A = np.array([[0.95, 0, 0.15],[0.05,0.8,0],[0,0.2,0.85]])
t5EigenStart = time.perf_counter_ns()
eigenVal, eigenVec = np.linalg.eig(A)
Pt5 = eigenVec
Pt5Inv = np.linalg.inv(Pt5)
D = np.array([[eigenVal[0], 0, 0],
            [0, eigenVal[1], 0],
            [0, 0, eigenVal[2]]])
Dexpt = SetLambda(D, 5)
outt5Eigen = Pt5@Dexpt@Pt5Inv@X0
t5EigenEnd = time.perf_counter_ns()
t5EigenTime = t5EigenEnd - t5EigenStart
print(f"\033[4mEigen Application\033[00m runtime when t= 5: \033[92m {t5EigenTime} \033[00m ns")
print(f"Value: {outt5Eigen} ")

Eigen Application runtime when t= 5:  263300  ns
Value: [[0.75613277-5.94747708e-17j]
 [0.15850167-1.36901072e-19j]
 [0.08536556-2.13000639e-17j]] 


เทียบเวลาเมื่อต้องการหา t ที่ค่า 500000

In [18]:
X = np.array([[0.95],[0.05],[0]])
A = np.array([[0.95, 0, 0.15],[0.05,0.8,0],[0,0.2,0.85]])
def findXt(A, X, t):
  for i in range(t):
    X = A@X
  return X
t500kTransformationStart = time.perf_counter_ns()
outt500kEigen = findXt(A, X, 500000)
t500kTransformationEnd = time.perf_counter_ns()
t500kTransTime = t500kTransformationEnd - t500kTransformationStart
print(f"\033[4mtransformation\033[00m runtime when t= 500000: \033[92m {t500kTransTime} \033[00m ns")
print(f"Value: {outt500kEigen} ")

transformation runtime when t= 500000:  381838800  ns
Value: [[0.63157895]
 [0.15789474]
 [0.21052632]] 


In [19]:
X0 = np.array([[0.95],[0.05],[0]])
A = np.array([[0.95, 0, 0.15],[0.05,0.8,0],[0,0.2,0.85]])
t500kEigenStart = time.perf_counter_ns()
eigenVal, eigenVec = np.linalg.eig(A)
Pt500k = eigenVec
Pt500kInv = np.linalg.inv(Pt5)
D = np.array([[eigenVal[0], 0, 0],
            [0, eigenVal[1], 0],
            [0, 0, eigenVal[2]]])
Dexpt = SetLambda(D, 5)
outt500kEigen = Pt500k@Dexpt@Pt500kInv@X0
t500kEigenEnd = time.perf_counter_ns()
t500kEigenTime = t500kEigenEnd - t500kEigenStart
print(f"\033[4mEigen Application\033[00m runtime when t= 500000: \033[92m {t500kEigenTime} \033[00m ns")
print(f"Value: {outt500kEigen} ")

Eigen Application runtime when t= 500000:  269200  ns
Value: [[0.75613277-5.94747708e-17j]
 [0.15850167-1.36901072e-19j]
 [0.08536556-2.13000639e-17j]] 


จากการทำงานทั้งหมด จะได้เวลาสรุปดังตารางด้านล่าง

In [20]:
print(f"{'t size':6s}|{'Transformation':13s}| {'EigenApp':10s}")
if t5TransTime > t5EigenTime:
  print(f"{5:6d}|\033[91m{t5TransTime:13d} \033[0m| \033[92m{t5EigenTime:10d} \033[0m")
else:
  print(f"{5:6d}|\033[92m{t5TransTime:13d} \033[0m| \033[91m{t5EigenTime:10d} \033[0m")
if t500kTransTime > t500kEigenTime:
  print(f"{500000:6d}|\033[91m{t500kTransTime:13d} \033[0m| \033[92m{t500kEigenTime:10d} \033[0m")
else:
  print(f"{500000:6d}|\033[92m{t500kTransTime:13d} \033[0m| \033[91m{t500kEigenTime:10d} \033[0m")  


t size|Transformation| EigenApp  
     5|        68700 |     263300 
500000|    381838800 |     269200 


2. เราสามารถทำการคิดค่าสถานะการติดเชื้อเมื่อมีค่าที่คงที่แล้วได้โดยที่ไม่จำเป็นต้องทำการคูณไปเรื่อยๆจนกว่าจะได้ช่วงสัปดาห์ที่ต้องการได้หรือไม่ <br>
**คำตอบ** สามารถทำได้โดยใช้ **eigenValue** และ **eigenVector** ตามที่อธิบายไว้ในหัวข้อที่3.